# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [3]:
# Import torch
import torch

# Create a random tensor with shape (7, 7)
tensor_a = torch.rand(7, 7)
print(tensor_a, tensor_a.shape)

tensor([[0.6590, 0.4476, 0.2337, 0.8059, 0.5991, 0.0430, 0.1172],
        [0.8920, 0.3810, 0.1439, 0.5371, 0.5951, 0.5377, 0.9390],
        [0.1211, 0.7740, 0.2517, 0.6870, 0.5262, 0.3248, 0.1571],
        [0.9188, 0.5835, 0.4155, 0.3108, 0.8960, 0.2312, 0.3960],
        [0.8854, 0.2928, 0.7674, 0.3583, 0.2892, 0.9020, 0.9913],
        [0.4604, 0.0084, 0.2595, 0.4246, 0.4453, 0.9682, 0.1606],
        [0.6791, 0.8480, 0.3201, 0.0483, 0.6787, 0.2011, 0.8981]]) torch.Size([7, 7])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [4]:
# Create another random tensor with shape (1, 7)
tensor_b = torch.rand(1, 7)

# Transpose tensor_b to match the dimensions for matrix multiplication
tensor_b_transposed = tensor_b.T

# Perform matrix multiplication
result = torch.matmul(tensor_a, tensor_b_transposed)
print(result,result.shape)

tensor([[1.8526],
        [2.0790],
        [1.5976],
        [2.5416],
        [2.1579],
        [1.1897],
        [2.3320]]) torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [7]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor_a = torch.rand(7, 7)
tensor_b = (torch.rand(1, 7)).T 

# Matrix multiply tensors
result = torch.matmul(tensor_a, tensor_b)

print(result, result.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [8]:
# Set random seed on the GPU
if torch.cuda.is_available():
    torch.cuda.manual_seed(1234)
    print("Random seed set on GPU")



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [9]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device available:", device)

# Create two random tensors on GPU
tensor_a = torch.rand(2, 3).to(device)
tensor_b = torch.rand(2, 3).to(device)

print(tensor_a, tensor_b)

Device available: cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [10]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(tensor_a, tensor_b.T)
print(result, result.shape)


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]) torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [12]:
# Find max
max_val = torch.max(result)

# Find min
min_val = torch.min(result)

print("Max:", max_val, "Min:", min_val)

Max: tensor(0.5617) Min: tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [13]:
# Find arg max
arg_max = torch.argmax(result)

# Find arg min
arg_min = torch.argmin(result)

print("Argmax:", arg_max, "Argmin:", arg_min)

Argmax: tensor(3) Argmin: tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [16]:
# Set seed
torch.manual_seed(7)


# Create random tensor
tensor_x = torch.rand(1, 1, 1, 10)

# Remove single dimensions
tensor_x_squeezed = torch.squeeze(tensor_x)

# Print out tensors and their shapes
print(tensor_x, tensor_x.shape)
print(tensor_x_squeezed, tensor_x_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
